<?php

function banner_simples_preprocess_paragraph__banner_simples(&$variables) {
  $paragraph = $variables['paragraph'];
  if (!$paragraph->field_imagem_banner->isEmpty()) {
    $image = $paragraph->field_imagem_banner->entity->url();
    $variables['attributes']['style'][] = 'background-image: url("' . $image . '");';
    $variables['attributes']['style'][] = 'background-size: none;';
    $variables['attributes']['style'][] = 'background-position: center center;';
  }
}